export const SUBJECTS: string[] = [
  "Medicine",
  "Surgery",
  "Anatomy",
  "Physiology",
  "Pathology",
  "Pharmacology",
  "Microbiology",
  "Radiology",
  "Biochemistry",
  "Ophthalmology",
  "Gynaecology & Obstetrics",
  "Social & Preventive Medicine",
  "Anaesthesia",
  "Pediatrics",
  "Orthopedics",
  "ENT",
  "Dermatology",
  "Psychiatry",
  "Forensic Medicine",
  "Dental",
];
